# job template
# File: templates/jobs.yml
jobs:
- job: MyUbuntuJob
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - script: cd $(Build.SourcesDirectory)/ ; ls -ltr ;
    displayName: Step MyUbuntuJob step
  
