stages:
  - stage: Deploy
    displayName: Deploy stage

    jobs:
      - deployment: Deploy
        environment: $(ADO_ENVIRONMENT_NAME)
        displayName: Deploy
        strategy:
          runOnce:
            deploy:
              steps:


                - task: KubernetesManifest@0
                  name: bake_secret_provider_class
                  displayName: Bake changes to SecretProviderClass
                  inputs:
                    action: 'bake'
                    namespace: default
                    helmChart: '$(Build.SourcesDirectory)/engage-devops/helm/secret-provider'
                    overrideFiles: '$(Build.SourcesDirectory)/$(GIT_REPO_NAME)/helm/secrets.yaml'
                    renderType: 'helm'


                - task: KubernetesManifest@0
                  name: bake_service
                  displayName: Bake changes to service
                  inputs:
                    action: 'bake'
                    namespace: default
                    helmChart: '$(Build.SourcesDirectory)/engage-devops/applications/$(SERVICE_NAME)/helm/service'
                    renderType: 'helm'
                    overrideFiles: |
                      $(Build.SourcesDirectory)/engage-devops/applications/$(SERVICE_NAME)/helm/service/${{ parameters.TARGET_ENV }}/values.yaml

                - script: |
                    echo "Manifests being deployed:"
                    cat $(bake_service.manifestsBundle)
                  displayName: 'List manifests'                    

