# run a container
# Node.js
# Build a Node.js project that uses Node 12.13.0-alpine.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.13.0'
  displayName: 'Install Node.js'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'your-dockerhub-username/your-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

- task: CopyFiles@2
  inputs:
    contents: '**'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'